### ISSUE TITLE
Error with account.call

### ISSUE THREAD

**Issue by charlietilt** [Shard-Labs/starknet-hardhat-plugin#113]
## Summary
I am getting an error when trying to `call` a contract `@view` method. I get the same issue locally (shardlabs/starknet-devnet:0.2.2-arm) as I do on `alpha`.

I have attached the test contract and test spec file:
- [Foo.cairo](https://gist.github.com/charlietilt/f0486be8a48e5a020b96c1166f8e2556)
- [Foo.spec.js](https://gist.github.com/charlietilt/74c60062993a0e7f1a251e32ad38339b)
- [hardhat.config.js](https://gist.github.com/charlietilt/7cf959e08c5ee13e719b84c1831ab42b)
- [package.json](https://gist.github.com/charlietilt/65a7f4980b19aba2b5cb4da43e37590e)
- [package-lock.json](https://gist.github.com/charlietilt/5fea4ebc71d8b2aa2bac5bd7f0eb28d7)

Here is the error I received when running on alpha:
```
HardhatPluginError: Could not perform call on __execute__:
Got BadRequest while trying to access https://alpha4.starknet.io/feeder_gateway/call_contract?blockNumber=pending. Status code: 500; text: {"code": "StarknetErrorCode.TRANSACTION_FAILED", "message": "Error at pc=0:134:\nSignature (1673925406664288395194014266915634121255994698743581988859762645609544057099, 3267185712093669269158180303132515657399762799212131849029619600604002588995), is invalid, with respect to the public key 2001874741716233317693150946109625889536559338446422799470279717300847451737, and the message hash 513841997411178000137272081953651204656394336317085175571681275522893698968.\nCairo traceback (most recent call last):\nUnknown location (pc=0:921)\nUnknown location (pc=0:865)\nUnknown location (pc=0:477)\nUnknown location (pc=0:394)"}.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/services/external_api/base_client.py", line 120, in _send_request
    raise BadRequest(status_code=response.status, text=text)
services.external_api.base_client.BadRequest: HTTP error ocurred. Status: 500. Text: {"code": "StarknetErrorCode.TRANSACTION_FAILED", "message": "Error at pc=0:134:\nSignature (1673925406664288395194014266915634121255994698743581988859762645609544057099, 3267185712093669269158180303132515657399762799212131849029619600604002588995), is invalid, with respect to the public key 2001874741716233317693150946109625889536559338446422799470279717300847451737, and the message hash 513841997411178000137272081953651204656394336317085175571681275522893698968.\nCairo traceback (most recent call last):\nUnknown location (pc=0:921)\nUnknown location (pc=0:865)\nUnknown location (pc=0:477)\nUnknown location (pc=0:394)"}
Error: BadRequest: HTTP error ocurred. Status: 500. Text: {"code": "StarknetErrorCode.TRANSACTION_FAILED", "message": "Error at pc=0:134:\nSignature (1673925406664288395194014266915634121255994698743581988859762645609544057099, 3267185712093669269158180303132515657399762799212131849029619600604002588995), is invalid, with respect to the public key 2001874741716233317693150946109625889536559338446422799470279717300847451737, and the message hash 513841997411178000137272081953651204656394336317085175571681275522893698968.\nCairo traceback (most recent call last):\nUnknown location (pc=0:921)\nUnknown location (pc=0:865)\nUnknown location (pc=0:477)\nUnknown location (pc=0:394)"}

      at StarknetContract.<anonymous> (node_modules/@shardlabs/starknet-hardhat-plugin/src/types.ts:520:19)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/@shardlabs/starknet-hardhat-plugin/dist/src/types.js:28:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by FabijanC** [comment]
Just in case, can you also provide your package.json and package-lock.json (or yarn.lock if you are using that).

**Comment by FabijanC** [comment]
Good news is that I'm finally able to reproduce this. Still trying to figure out what's causing it.

**Comment by charlietilt** [comment]
> Good news is that I'm finally able to reproduce this. Still trying to figure out what's causing it.

@FabijanC, just curious if you guys have made any progress on this one?

**Comment by FabijanC** [comment]
> > Good news is that I'm finally able to reproduce this. Still trying to figure out what's causing it.
> 
> @FabijanC, just curious if you guys have made any progress on this one?

Just tested it with the unreleased upcoming version, should be fixed there (for both OpenZeppelin and Argent accounts).

**Comment by charlietilt** [comment]
That is excellent, thank you👍🏻
