### ISSUE TITLE
Remove isWsl flag for WSL.

### ISSUE THREAD

**Issue by mikiw** [Shard-Labs/starknet-hardhat-plugin#235]
Couple of months ago this code was introduced to fix the problem that @ivpavici had with WSL and [starknet-hardhat-plugin](https://github.com/Shard-Labs/starknet-hardhat-plugin). So now in utils.ts we have this code that is supposed to fix some issues with WSL:

```
/**
 * Adapts `url` by replacing localhost and 127.0.0.1 with `host.internal.docker`
 * @param url string representing the url to be adapted
 * @returns adapted url
 */
export function adaptUrl(url: string): string {
    if (process.platform === MACOS_PLATFORM || isWsl) {
        for (const protocol of ["http://", "https://", ""]) {
            for (const host of ["localhost", "127.0.0.1"]) {
                if (url === `${protocol}${host}`) {
                    return `${protocol}${DOCKER_HOST}`;
                }

                const prefix = `${protocol}${host}:`;
                if (url.startsWith(prefix)) {
                    return url.replace(prefix, `${protocol}${DOCKER_HOST}:`);
                }
            }
        }
    }
```

but it seems that currently, this code is causing a problem with running quick test:
```npx hardhat test test/quick-test.ts```

error:
```
       should work for a fresh deployment:
     StarknetPluginError: Could not perform call on getPublicKey.
Got ClientConnectorError while trying to access http://host.docker.internal:5050/feeder_gateway/call_contract?blockNumber=pending
      at StarknetContract.<anonymous> (node_modules/@shardlabs/starknet-hardhat-plugin/src/types.ts:602:19)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/@shardlabs/starknet-hardhat-plugin/dist/src/types.js:28:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

so `|| isWsl` in if the statment should be removed.

**Comment by FabijanC** [comment]
This is probably responsible: https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/210
