### ISSUE TITLE
`Account.delare` errors out when running `test/declare-deploy.test.ts` locally

### ISSUE THREAD

**Issue by jessupjn** [Shard-Labs/starknet-hardhat-plugin#271]
I am erroring out when I at `account.declare(contractFactory)` - and I am able to reproduce the issue when I run the declare test in the `starknet-hardhat-example` repo ([test/declare-deploy.test.ts](https://github.com/Shard-Labs/starknet-hardhat-example/blob/master/test/declare-deploy.test.ts)).

```
StarknetPluginError: Could not declare class: Got ClientConnectorError while trying to access http://127.0.0.1:5050/feeder_gateway/get_nonce?contractAddress=0x40e9651ef7f8b36cc3ef6b8722e263bacd5d52896901de6db79ab62a4e767d1&blockNumber=pending.
```

**Comment by FabijanC** [comment]
The error is saying that the plugin is trying to connect to `127.0.0.1:5050`, that means you're probably connecting to `integrated-devnet` or an external `starknet-devnet`. You can read more about these networks here: [link](https://github.com/Shard-Labs/starknet-hardhat-plugin#runtime-network).

A few questions that will help with debugging:
1. Which command did you run to get this?
2. Can you show your `hardhat.config.ts` file?
3. What do you get when you run `npx hardhat starknet-plugin-version`? You can omit `npx` if you have `hardhat` installed locally.

**Comment by jessupjn** [comment]
I havent modified `hardhat.config.ts` in the repository.

Version: 0.6.8
```bash
❯ npx hardhat starknet-plugin-version
Starknet plugin using dockerized environment (shardlabs/cairo-cli:0.10.3-arm)
Version: 0.6.8
```

Here is my command + output
```bash
❯ npx hardhat test test/declare-deploy.test.ts 
Starknet plugin using dockerized environment (shardlabs/cairo-cli:0.10.1-arm)
Using network integrated-devnet at http://127.0.0.1:5050

  Class declaration
    1) should declare and deploy a class

  0 passing (6s)
  1 failing

  1) Class declaration
       should declare and deploy a class:
     StarknetPluginError: Could not declare class: Got ClientConnectorError while trying to access http://127.0.0.1:5050/feeder_gateway/get_nonce?contractAddress=0x4cbdfcd49fae0ecd3a69a6fc2c96c2685bfc2831e513033ffbb0541d3fbf66c&blockNumber=pending.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 5050)
```

I also should note that I am able to run `test/decode-events.test.ts` successfully... will update the repo to `0.7.0` and try again
